-- Ejecutar una sola vez en Supabase SQL Editor.
alter table public.campaigns
add column if not exists plan text not null default 'FREE';

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mp_subscription_id text unique,
  mp_plan_id text,
  plan text not null default 'FREE',
  status text default 'pending',
  payer_email text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists subscriptions_user_idx on public.subscriptions(user_id);
create index if not exists subscriptions_mp_idx on public.subscriptions(mp_subscription_id);
alter table public.subscriptions enable row level security;
drop policy if exists "Users can view own subscription" on public.subscriptions;
create policy "Users can view own subscription" on public.subscriptions for select using (auth.uid() = user_id);
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.subscriptions to service_role;
grant usage, select on sequence public.subscriptions_id_seq to service_role;
