-- AdMaker IA: base de datos para cuentas e historial.
-- Pega TODO este archivo en Supabase > SQL Editor > New query y pulsa Run.

create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Sin nombre',
  product_price text default '',
  description text default '',
  audience text default '',
  goal text default '',
  result jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists campaigns_user_created_idx on public.campaigns(user_id, created_at desc);

alter table public.campaigns enable row level security;

drop policy if exists "Users can view own campaigns" on public.campaigns;
drop policy if exists "Users can insert own campaigns" on public.campaigns;
drop policy if exists "Users can delete own campaigns" on public.campaigns;

create policy "Users can view own campaigns" on public.campaigns
  for select using (auth.uid() = user_id);

create policy "Users can insert own campaigns" on public.campaigns
  for insert with check (auth.uid() = user_id);

create policy "Users can delete own campaigns" on public.campaigns
  for delete using (auth.uid() = user_id);
